### ISSUE TITLE
Error compile :/

### ISSUE THREAD

**Issue by kernkode** [sampgo/base#1]
Any idea why I get these errors when compiling?

`> Environment:
>   GOPATH=C:/Go
> Directory: C:\Users\DiegoAlex\Desktop\gmod
> Command: C:/Go/bin\go.exe run -v C:\Users\DiegoAlex\Desktop\gmod\main.go
> Output:
_/C_/Users/DiegoAlex/Desktop/gmod/sampgo
# _/C_/Users/DiegoAlex/Desktop/gmod/sampgo
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x002.o: in function `cgo_b62a9b6d8ba9_Cfunc_OnPlayerConnect':

/tmp/go-build/cgo-gcc-prolog:53: undefined reference to `OnPlayerConnect@4'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x002.o: in function `cgo_b62a9b6d8ba9_Cfunc_constToNonConst':

/tmp/go-build/cgo-gcc-prolog:71: undefined reference to `constToNonConst'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_ApplyActorAnimation':

/tmp/go-build/cgo-gcc-prolog:61: undefined reference to `_imp__sampgdk_ApplyActorAnimation'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_ClearActorAnimations':

/tmp/go-build/cgo-gcc-prolog:80: undefined reference to `_imp__sampgdk_ClearActorAnimations'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_CreateActor':

/tmp/go-build/cgo-gcc-prolog:102: undefined reference to `_imp__sampgdk_CreateActor'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_CreateVehicle':

/tmp/go-build/cgo-gcc-prolog:129: undefined reference to `_imp__sampgdk_CreateVehicle'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_DestroyActor':

/tmp/go-build/cgo-gcc-prolog:148: undefined reference to `_imp__sampgdk_DestroyActor'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_DestroyVehicle':

/tmp/go-build/cgo-gcc-prolog:167: undefined reference to `_imp__sampgdk_DestroyVehicle'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_GetActorFacingAngle':

/tmp/go-build/cgo-gcc-prolog:187: undefined reference to `_imp__sampgdk_GetActorFacingAngle'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_GetActorPos':

/tmp/go-build/cgo-gcc-prolog:209: undefined reference to `_imp__sampgdk_GetActorPos'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_GetActorVirtualWorld':

/tmp/go-build/cgo-gcc-prolog:227: undefined reference to `_imp__sampgdk_GetActorVirtualWorld'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_GetPlayerFacingAngle':

/tmp/go-build/cgo-gcc-prolog:247: undefined reference to `_imp__sampgdk_GetPlayerFacingAngle'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_GetPlayerPos':

/tmp/go-build/cgo-gcc-prolog:269: undefined reference to `_imp__sampgdk_GetPlayerPos'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_GetVehicleDistanceFromPoint':

/tmp/go-build/cgo-gcc-prolog:290: undefined reference to `_imp__sampgdk_GetVehicleDistanceFromPoint'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_IsActorStreamedIn':

/tmp/go-build/cgo-gcc-prolog:310: undefined reference to `_imp__sampgdk_IsActorStreamedIn'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_IsPlayerInRangeOfPoint':

/tmp/go-build/cgo-gcc-prolog:333: undefined reference to `_imp__sampgdk_IsPlayerInRangeOfPoint'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_IsValidVehicle':

/tmp/go-build/cgo-gcc-prolog:352: undefined reference to `_imp__sampgdk_IsValidVehicle'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_SendClientMessage':

/tmp/go-build/cgo-gcc-prolog:373: undefined reference to `_imp__sampgdk_SendClientMessage'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_SendClientMessageToAll':

/tmp/go-build/cgo-gcc-prolog:393: undefined reference to `_imp__sampgdk_SendClientMessageToAll'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_SetActorFacingAngle':

/tmp/go-build/cgo-gcc-prolog:413: undefined reference to `_imp__sampgdk_SetActorFacingAngle'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_SetActorPos':

/tmp/go-build/cgo-gcc-prolog:435: undefined reference to `_imp__sampgdk_SetActorPos'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_SetActorVirtualWorld':

/tmp/go-build/cgo-gcc-prolog:455: undefined reference to `_imp__sampgdk_SetActorVirtualWorld'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_SetPlayerFacingAngle':

/tmp/go-build/cgo-gcc-prolog:475: undefined reference to `_imp__sampgdk_SetPlayerFacingAngle'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_SetPlayerPos':

/tmp/go-build/cgo-gcc-prolog:497: undefined reference to `_imp__sampgdk_SetPlayerPos'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_SpawnPlayer':

/tmp/go-build/cgo-gcc-prolog:516: undefined reference to `_imp__sampgdk_SpawnPlayer'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x003.o: in function `cgo_b62a9b6d8ba9_Cfunc_nonConstToConst':

/tmp/go-build/cgo-gcc-prolog:546: undefined reference to `nonConstToConst'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x004.o: in function `cgo_b62a9b6d8ba9_Cfunc_GetPlayerName':

/tmp/go-build/cgo-gcc-prolog:54: undefined reference to `_imp__sampgdk_GetPlayerName'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x004.o: in function `cgo_b62a9b6d8ba9_Cfunc_SetPlayerName':

/tmp/go-build/cgo-gcc-prolog:73: undefined reference to `_imp__sampgdk_SetPlayerName'

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: $WORK\b002\_x005.o: in function `cgo_b62a9b6d8ba9_Cfunc_goLogprintf':

/tmp/go-build/cgo-gcc-prolog:49: undefined reference to `goLogprintf'

collect2.exe: error: ld returned 1 exit status
# _/C_/Users/DiegoAlex/Desktop/gmod/sampgo
In file included from sampgo/sampgdk/sampgdk.h:135,
                 from sampgo/sampgdk/main.h:4,
                 from callbacks.go:14,
                 from _cgo_export.c:4:
sampgo/sampgdk/plugincommon.h:35:10: note: #pragma message: Warning: Not using a VC++ compiler.
   35 |  #pragma message "Warning: Not using a VC++ compiler."
      |          ^~~~~~~
# _/C_/Users/DiegoAlex/Desktop/gmod/sampgo
In file included from sampgo/sampgdk/sampgdk.h:135,
                 from sampgo/sampgdk/main.h:4,
                 from sampgo\callbacks.go:14:
sampgo/sampgdk/plugincommon.h:35:10: note: #pragma message: Warning: Not using a VC++ compiler.
   35 |  #pragma message "Warning: Not using a VC++ compiler."
      |          ^~~~~~~
# _/C_/Users/DiegoAlex/Desktop/gmod/sampgo
In file included from sampgo/sampgdk/sampgdk.h:135,
                 from sampgo/sampgdk/main.h:4,
                 from sampgo\natives.go:14:
sampgo/sampgdk/plugincommon.h:35:10: note: #pragma message: Warning: Not using a VC++ compiler.
   35 |  #pragma message "Warning: Not using a VC++ compiler."
      |          ^~~~~~~
# _/C_/Users/DiegoAlex/Desktop/gmod/sampgo
In file included from sampgo/sampgdk/sampgdk.h:135,
                 from sampgo/sampgdk/main.h:4,
                 from sampgo\player.go:14:
sampgo/sampgdk/plugincommon.h:35:10: note: #pragma message: Warning: Not using a VC++ compiler.
   35 |  #pragma message "Warning: Not using a VC++ compiler."
      |          ^~~~~~~
# _/C_/Users/DiegoAlex/Desktop/gmod/sampgo
In file included from sampgo/sampgdk/sampgdk.h:135,
                 from sampgo/sampgdk/main.h:4,
                 from sampgo\sampgo.go:14:
sampgo/sampgdk/plugincommon.h:35:10: note: #pragma message: Warning: Not using a VC++ compiler.
   35 |  #pragma message "Warning: Not using a VC++ compiler."
      |          ^~~~~~~
> Elapsed: 19.372s
> Result: Error`

**Comment by alextwothousand** [comment]
Use the dockerfile for the time being. A fix for windows is in the works.

**Comment by kernkode** [comment]
I hope they solve it as soon as possible 😕
